version: "3"

services:
    db:
        image: postgres:12.3
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=passwd
        networks:
            - app_net
        volumes:
            - db_vol:/var/lib/postgresql/data
    db-admin:
        image: adminer:4.7.7
        ports:
            - 8999:8080
        networks:
            - app_net
    nginx:
        image: nginx:1.19.0
        ports:
            - 80:80
        networks:
            - app_net
        volumes:
            - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${PWD}/app:/sites/app

networks:
    app_net:

volumes:
    db_vol: